auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("addListing", views.add, name="add"),
    path("category", views.category, name="category"),
    path("listing/<int:list_id>", views.listing, name="listing"),
    path("bid/<int:list_id>", views.place_bid, name="place_bid"),
    path("comment/<int:list_id>", views.comment, name="comment"),
    path("addWatchlist/<int:list_id>", views.add_watchlist, name="add_watchlist"),
    path("removeWatchlist/<int:list_id>", views.remove_watchlist, name="remove_watchlist"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("closeAuction/<int:list_id>", views.close_auction, name="close_auction"),
    path("wonAuction", views.won_auction, name="won_auction"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings


class User(AbstractUser):
    pass


class Category(models.Model):
    categoryTitle = models.CharField(max_length=60)

    def __str__(self):
        return self.categoryTitle


class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="userBids")
    value = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.value}$ bid by {self.user}"


class Listing(models.Model):
    title = models.CharField(max_length=64)
    price = models.ForeignKey(Bid, on_delete=models.CASCADE, blank=True, null=True, related_name="bid")
    created = models.DateTimeField(auto_now_add=True)
    photoUrl = models.CharField(max_length=1200, blank=True)
    description = models.CharField(max_length=250, blank=False)
    isOpen = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True, related_name="items")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True, related_name="listings")
    watchlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="watchlist", blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    comment = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments", null=True, blank=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listingComments", blank=True, null=True)

    def __str__(self):
        return f"{self.owner} commented on {self.listing}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User, Listing, Category, Comment, Bid


def index(request):
    listings: list = Listing.objects.filter(isOpen=True)

    return render(request, "auctions/index.html", {
        "listings": listings,
    })


@login_required
def add(request):
    if request.method == "POST":
        title = request.POST["title"]
        description = request.POST["description"]
        image_url = request.POST["imageUrl"]
        user = request.user

        price = Bid(value=request.POST["startingBid"], user=user)
        price.save()

        new_list = Listing(
            title=title,
            description=description,
            price=price,
            photoUrl=image_url,
            category=Category.objects.get(categoryTitle=request.POST["category"]),
            owner=user
        )

        new_list.save()

        return HttpResponseRedirect(reverse("auctions:index"))

    return render(request, "auctions/add.html", {
        "category_list": Category.objects.all(),
    })


@login_required()
def add_watchlist(request, list_id):
    if request.method == "POST":
        current_list = Listing.objects.get(pk=list_id)
        current_list.watchlist.add(request.user)
        return HttpResponseRedirect(reverse("auctions:listing", args=(list_id,)))


@login_required()
def remove_watchlist(request, list_id):
    if request.method == "POST":
        current_list = Listing.objects.get(pk=list_id)
        current_list.watchlist.remove(request.user)
        return HttpResponseRedirect(reverse("auctions:listing", args=(list_id,)))


@login_required()
def watchlist(request):
    user = request.user
    listings = user.watchlist.all()

    return render(request, "auctions/watchlist.html", {
        "listings": listings,
    })


def category(request):
    if request.method == "POST":
        category = Category.objects.get(categoryTitle=request.POST["category"])

        return render(request, "auctions/index.html", {
            "listings": Listing.objects.filter(isOpen=True, category=category),
            "category_list": Category.objects.all(),
        })

    return render(request, "auctions/category.html", {
        "category_list": Category.objects.all(),
    })


def listing(request, list_id):
    current_list = Listing.objects.get(pk=list_id)
    comments = current_list.listingComments.all()
    isInWatchlist = request.user in current_list.watchlist.all()
    # bids = Bid.objects.filter(bid=current_list)
    # print(len(bids), bids)

    return render(request, "auctions/listing.html", {
        "listing": current_list,
        "isInWatchlist": isInWatchlist,
        "comments": comments,
    })


def place_bid(request, list_id):
    new_bid = float(request.POST["bid"])
    current_list = Listing.objects.get(pk=list_id)

    comments = current_list.listingComments.all()
    isInWatchlist = request.user in current_list.watchlist.all()

    if new_bid <= current_list.price.value:

        return render(request, "auctions/listing.html", {
            "listing": current_list,
            "isInWatchlist": isInWatchlist,
            "comments": comments,
            "message": "Bid Update Failed!"
        })

    updated_bid = Bid(value=new_bid, user=request.user)
    updated_bid.save()
    current_list.price = updated_bid
    current_list.save()

    return render(request, "auctions/listing.html", {
            "listing": current_list,
            "isInWatchlist": isInWatchlist,
            "comments": comments,
            "message": "Successfully Updated Bid!"
        })


@login_required()
def close_auction(request, list_id):
    current_list = Listing.objects.get(pk=list_id)
    current_list.isOpen = False
    current_list.save()
    return HttpResponseRedirect(reverse("auctions:index"))


@login_required()
def won_auction(request):
    listings = Listing.objects.filter(isOpen=False)

    listings: list = [each for each in listings if each.price.user == request.user]
    # for each in listings:
    #     if each.price.user == user:
    #         new_listing.append(each)

    return render(request, "auctions/index.html", {
        "listings": listings,
    })


@login_required()
def comment(request, list_id):
    if request.method == "POST":
        comment = request.POST["comment"]
        owner = request.user
        current_listing = Listing.objects.get(pk=list_id)
        new_comment = Comment(comment=comment, owner=owner, listing=current_listing)
        new_comment.save()
        return HttpResponseRedirect(reverse("auctions:listing", args=(list_id,)))


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

auctions/templates/auctions/add.html
{% extends "auctions/layout.html" %}

{% block body %}
    <form action="{% url 'auctions:add' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <input type="text" class="form-control" name="title" placeholder="Title" autocomplete="off">
        </div>

        <div class="form-group">
            <input type="text" class="form-control" name="description" placeholder="Description" autocomplete="off">
        </div>

        <div class="form-group">
            <input type="text" id="price" class="form-control" name="startingBid" placeholder="Starting Bid" autocomplete="off">
        </div>

        <div class="form-group">
            <input type="text" class="form-control" name="imageUrl" placeholder="Image URL" autocomplete="off">
        </div>

        <div class="form-group">
            <select class="form-control" name="category">
                {% for each in category_list %}
                    <option value="{{ each }}">{{ each }}</option>
                {% endfor %}
            </select>

        </div>

        <input type="submit" class="btn btn-secondary" value="Create">


    </form>

    <script>
        document.addEventListener("submit", event => {
            let floatValue = parseFloat(document.querySelector("#price").value);
            if (!isNaN(floatValue) && isFinite(floatValue)) {
                return;
            }
            alert("Price must be a number.");
            event.preventDefault()

        })
    </script>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %} {% block body %}

<h4 class="text-center mb-4">Browse by Category</h4>

<!-- Category Container -->
<div
    class="container p-4 border rounded shadow-sm"
    style="max-width: 700px; background-color: #f8f9fa"
>
    <div class="row justify-content-center g-3">
        {% for category in category_list %}
        <div class="col-6 col-md-4">
            <form action="{% url 'auctions:category' %}" method="post">
                {% csrf_token %}

                <button
                    type="submit"
                    name="category"
                    value="{{ category.categoryTitle }}"
                    class="btn btn-outline-primary w-100 py-2 fw-bold"
                    style="font-size: 16px; transition: 0.3s"
                >
                    {{ category.categoryTitle }}
                </button>
            </form>
        </div>
        {% endfor %}
    </div>
    <!-- End row -->
</div>
<!-- End container -->

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %} {% block body %} {% if not listings %}
<h2>No Listings Available!</h2>
{% else %}
<h2 class="mb-4">Active Listings</h2>

<div class="d-flex flex-wrap justify-content-start gap-5 px-3">
    {% for listing in listings %}
    <div class="card shadow-sm" style="width: 300px">
        <img
            src="{{ listing.photoUrl|default:'/static/images/placeholder.jpg' }}"
            class="card-img-top"
            alt="{{ listing.title }}"
            style="
                height: 180px;
                object-fit: contain;
                background-color: #f8f9fa;
            "
        />

        <div class="card-body" style="font-size: 14px">
            <a
                href="{% url 'auctions:listing' listing.id %}"
                class="text-decoration-none text-primary"
            >
                <h6 class="card-title">{{ listing.title }}</h6>
            </a>
            <p class="card-text text-muted">
                {{ listing.description|truncatechars:80 }}
            </p>
            <p class="card-text font-weight-bold">
                ${{ listing.price.value|floatformat:2 }}
            </p>
            <p class="card-text">
                <small class="text-muted"
                    >Category: {{ listing.category }}</small
                >
            </p>
            <p class="card-text">
                <small class="text-muted"
                    >Created at {{ listing.created }}</small
                >
            </p>
        </div>
    </div>
    {% endfor %}
</div>

{% endif %} {% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %} Signed in as
            <strong>{{ user.username }}</strong>. {% else %} Not signed in.
            {%endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}"
                    >Active Listings</a
                >
            </li>
            {% if user.is_authenticated %}
            <li>
                <a class="nav-link" href="{% url 'auctions:add' %}"
                    >Add Listing</a
                >
            </li>

            <li>
                <a class="nav-link" href="{% url 'auctions:watchlist' %}"
                    >Watchlist</a
                >
            </li>

            <li>
                <a class="nav-link" href="{% url 'auctions:won_auction' %}"
                    >Closed</a
                >
            </li>

            <li>
                <a class="nav-link" href="{% url 'auctions:category' %}"
                    >Categories</a
                >
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:logout' %}"
                    >Log Out</a
                >
            </li>

            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:register' %}"
                    >Register</a
                >
            </li>
            {% endif %}
        </ul>
        <hr />
        {% block body %} {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %} {% block body %}

<div class="card mb-3" style="max-width: 100%; border: none">
    {% if message %}
    <div class="alert alert-primary" role="alert">{{ message }}</div>

    {% endif %} {% if user == listing.price.user and not listing.isOpen %}
    <div class="alert alert-primary" role="alert">
        You have won this auction.
    </div>

    {% endif %} {% if user.is_authenticated %} {% if isInWatchlist %}
    <form
        method="post"
        action="{% url 'auctions:remove_watchlist' listing.id %}"
    >
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">
            Remove from Watchlist
        </button>
    </form>

    {% else %}
    <form method="post" action="{% url 'auctions:add_watchlist' listing.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Add to Watchlist</button>
    </form>

    {% endif %} {% endif %}

    <div style="max-width: 50%; border: 1px solid blue" class="my-3">
        <img
            alt="{{ listing.title }}"
            class="card-img-top"
            src="{{ listing.photoUrl }}"
        />
    </div>

    <div class="card-body">
        <h2 class="card-title">{{ listing.title }}</h2>
        <p class="card-text">{{ listing.description }}</p>
        <p class="card-text">${{ listing.price.value }}</p>

        {% if user.is_authenticated and listing.isOpen %}
        <form
            id="placeBid"
            method="post"
            action="{% url 'auctions:place_bid' listing.id %}"
        >
            {% csrf_token %}

            <div class="form-group">
                <input
                    type="number"
                    min="0"
                    name="bid"
                    class="form-control"
                    id="inputBid"
                />
                <input
                    type="hidden"
                    value="{{ listing.price.value }}"
                    id="currentListPrice"
                />
                <input
                    type="submit"
                    value="Place Bid"
                    class="btn btn-secondary"
                />
            </div>
        </form>

        {% if request.user == listing.owner %}
        <form action="{% url 'auctions:close_auction' listing.id %}">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Close Auction" />
        </form>
        {% endif %} {% endif %}

        <div class="my-3">
            <h5>Details</h5>
            <ul>
                <li>Listed by: {{ listing.owner }}</li>
                <li>Category: {{ listing.category }}</li>
            </ul>
            <p class="card-text">
                <small class="text-muted"
                    >Created at {{ listing.created}}</small
                >
            </p>
        </div>
    </div>

    <div class="">
        <h3>Comment</h3>
        <br />

        <ul class="list-group">
            {% for comment in comments %}
            <li class="list-group-item">
                <p>{{ comment.comment }}</p>
                <p>By {{ comment.owner }}</p>
                <p>{{ comment.created }}</p>
            </li>
            {% endfor %}
        </ul>

        {% if user.is_authenticated %}
        <div>
            <form
                action="{% url 'auctions:comment' listing.id %}"
                method="post"
            >
                {% csrf_token %}
                <textarea
                    class="form-control"
                    name="comment"
                    placeholder="Comment"
                ></textarea>
                <input type="submit" class="btn btn-primary" value="Comment" />
            </form>
        </div>
        {% endif %}
    </div>
</div>

<script>
    document.getElementById("placeBid").onsubmit = (event) => {
        let floatBid = parseFloat(document.querySelector("#inputBid").value);
        let currentListPrice = parseFloat(
            document.querySelector("#currentListPrice").value
        );
        console.log(floatBid, currentListPrice);

        if (floatBid <= currentListPrice) {
            alert("You must bid a bigger price than the latest bid!");
            event.preventDefault();
        }
    };
</script>

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>My Watchlist</h2>
    <br>

    {% if not listings %}
        <h2>No Watchlist!</h2>
    {% else %}

        {% for listing in listings %}

            <div class="card mb-3" style="max-width: 80%;">

                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ listing.photoUrl }}" class="img-fluid rounded-start" alt="{{ listing.title }}">
                    </div>

                    <div class="col-md-8">
                        <div class="card-body">

                            <a href="{% url 'auctions:listing' listing.id %}"><h5 class="card-title">{{ listing.title }}</h5></a>
                            <p class="card-text">{{ listing.description }}</p>
                            <p class="card-text">${{ listing.price.value }}</p>
                            <p class="card-text">Category: {{ listing.category }}</p>
                            <p class="card-text"><small class="text-muted">Created at {{ listing.created }}</small></p>
                        </div>
                    </div>
              </div>
            </div>
        {% endfor %}
    {% endif %}




{% endblock %}